name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      text_input:
        description: 'Enter text parameter'
        required: true
      dropdown_input:
        description: 'Select an option'
        required: true
        options:
          option1: Option 1
          option2: Option 2
          option3: Option 3

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Parameters
        run: |
          echo "Text input: ${{ github.event.inputs.text_input }}"
          echo "Dropdown input: ${{ github.event.inputs.dropdown_input }}"
